### ISSUE TITLE
Erro na instalação 

### ISSUE THREAD

**Issue by medeirosinacio** [opencodeco/stack#1]
Fui tentar instalar a stack para testar e a mesma apresenta erro no `make install` 🫠 Já removi e clonei novamente o projeto

```sheel
➜  stack git:(main) make install
Installing OpenCodeCo stack!
make: *** [install] Error 1
```

**Comment by adolfomenezes** [comment]
Fala @medeirosinacio !

Percebi que o erro ocorre quando ele tenta criar as networks:

https://github.com/opencodeco/stack/blob/2bbdb745b47ec0127e6f025a178e0e293fdeb586/Makefile#L8

Investigando um pouco mais, percebi que ele estava falhando nesse ponto:

https://github.com/opencodeco/stack/blob/2bbdb745b47ec0127e6f025a178e0e293fdeb586/stack#L22

Então coloquei o conteúdo que será filtrado dentro de aspas simples:

`NET=$(docker network ls | grep 'opencodeco')`

Então funcionou :rocket:! Consegue validar se essa alteração funciona para vc também?

**Comment by medeirosinacio** [comment]
Vou testar e aviso aqui, muito obrigado @adolfomenezes

**Comment by medeirosinacio** [comment]
Esqueci de voltar aqui, mas funcionou sim!
